version: '2'
services:
  arcadeanalytics-app:
    image: arcadeanalytics/arcadeanalytics:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - SPRING_DATASOURCE_URL=jdbc:postgresql://arcadeanalytics-postgresql:5432/arcadeanalytics
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=arcadeanalytics-elasticsearch:9300
      - SPRING_EMAIL_HOST=smtp.gmail.com
      - SPRING_EMAIL_PORT=587
      - SPRING_EMAIL_USERNAME=
      - SPRING_EMAIL_PASSWORD=
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
      - APPLICATION_PATH=/arcade
      - APPLICATION_MEDIAPATH=/content/media/
      - APPLICATION_STORAGE_PATH=/arcade/storage
      - APPLICATION_CONNECTORSPATH=/arcade-connectors
      - JAVA_OPTS=-DSSH_PRIV_KEY=/arcade/.ssh/id_rsa -DSSH_PUB_KEY=/arcade/.ssh/id_rsa.pub
    ports:
      - 8080:8080
    volumes:
      - ~/.arcade/:/arcade/
  arcadeanalytics-postgresql:
    image: postgres:9
    ports:
      - 5432:5432
    volumes:
      - ~/.arcade/arcadeanalytics/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=arcadeanalytics
      - POSTGRES_PASSWORD=
  arcadeanalytics-elasticsearch:
    image: elasticsearch:2.4.6
    volumes:
      - ~/.arcade/arcadeanalytics/elasticsearch/:/usr/share/elasticsearch/data/
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ports:
      - 9200:9200
      - 9300:9300
  arcadeanalytics-orientdb:
    extends:
      file: orientdb2.yml
      service: arcadeanalytics-orientdb
# uncomment to startup demo database
#  arcadeanalytics-postgresql-dvd-rental:
#    extends:
#      file: postgresql-dvd-rental.yml
#      service: arcadeanalytics-postgresql-dvd-rental
#  arcadeanalytics-mysql-sakila:
#    extends:
#      file: mysql-sakila.yml
#      service: arcadeanalytics-mysql-sakila
